### PR TITLE
added an about page with new text in english translation

### PR DESCRIPTION
**Pull request by Josh1794**
About page added with text in English Translation JSON

### CODE REVIEW

**Comment by Josh1794** [comment]
just added an image of the Web3 logo and our logo and used the grid layout from the platform page
Screen Shot 2020-06-28 at 4 20 31 PM
Screen Shot 2020-06-28 at 4 20 46 PM

**Comment by Josh1794** [comment]
Also the colons in the picture were removed as well

**Comment by zachdt** [comment]
Not sure if this branch source of issue #10

**Comment by zachdt** [comment]
Will need to programmatically add new team members, loop over both the board and contributors.

**Pull request merged**
